[build]
builder = "nixpacks"
buildCommand = "rm -rf package-lock.json && npm run clean && npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production" 